---
title: "create census shapefiles"
output: html_notebook
---


## packages

```{r}
# the tidyverse
library(dplyr)
library(forcats)
library(glue)

# utilities
library(here)

# mapping
library(sf)


```

## test run: DA

read file

```{r}

canada_da <- st_read(here::here("geography", "da_canada", "lda_000b16a_e.shp"))

saveRDS(canada_da, here("geography", "da_canada", "canada_da.RDS"))


```

filter to just B.C.

but wait, `PRUID` is a factor!

* see https://stat545.com/block029_factors.html#dropping-unused-levels


```{r}

ls.str(canada_da)
levels(canada_da$PRUID)

fct_count(canada_da$PRUID)

bc_da <- 
  canada_da %>%
  filter(PRUID == "59") 

fct_count(bc_da$PRUID)

bc_da <- 
  bc_da %>%
  mutate(PRUID = fct_drop(PRUID))

fct_count(bc_da$PRUID)


```

save as RDS file

```{r}

saveRDS(bc_da, here("geography", "bc_geog", "bc_da.RDS"))

```


```{r eval=FALSE}

bc_da <- readRDS(here("geography", "bc_geog", "bc_da.RDS"))

```

## function





```{r eval=FALSE}


# -- function

bcgeofile <- function(geolevel){
  assign(df, glue("canada_", geolevel))
  filter(df, PRUID == "59")
}

bcgeofile("ct")





```



## Census Sub-Division (CSD)


read file, filter to just B.C.

```{r}

geolevel <- "csd"


readgeofile <- function(geolevel){
  sourcefile <- glue("l", geolevel, "000b16a_e.shp")
  st_read(here::here("geography", glue(geolevel, "_canada"), sourcefile))
}


assign(glue("canada_", geolevel), 
       readgeofile(geolevel))

geog_obj <- glue("canada_", geolevel)

saveRDS(canada_csd, 
        here("geography", glue(geolevel, "_canada"), glue(geog_obj, ".RDS")))



bc_csd <- 
  canada_csd %>%
  filter(PRUID == "59") %>%
  mutate(PRUID = fct_drop(PRUID))

saveRDS(bc_ct, here("geography", "bc_geog", "bc_csd.RDS"))



```



### Census Division

```{r}


readgeofile <- function(geolevel){
  sourcefile <- glue("l", geolevel, "_000b16a_e.shp")
  st_read(here::here("geography", glue(geolevel, "_canada"), sourcefile))
}

geolevel <- "cd"

assign(glue("canada_", geolevel), 
       readgeofile(geolevel))

geog_obj <- glue("canada_", geolevel)

saveRDS(canada_cd, 
        here("geography", glue(geolevel, "_canada"), glue(geog_obj, ".RDS")))

# how can we use the `geo_obj` name to refer to the object of that name?
# down this path lies enquo and bang-bang, or a twist on assign, or...
# --- filter for B.C. values


bc_cd <- 
  canada_cd %>%
  filter(PRUID == "59") %>%
  mutate(PRUID = fct_drop(PRUID))

fct_count(bc_cd$PRUID)


saveRDS(bc_cd, here("geography", "bc_geog", "bc_cd.RDS"))


```


```{r eval=FALSE}

bc_ct <- readRDS(here("geography", "bc_geog", "bc_ct.RDS"))
bc_csd <- readRDS(here("geography", "bc_geog", "bc_csd.RDS"))
bc_cd <- readRDS(here("geography", "bc_geog", "bc_cd.RDS"))

```



## Reference

Statistics Canada, [Census: Geography](https://www12.statcan.gc.ca/census-recensement/2016/geo/index-eng.cfm)

Statistics Canada, [Boundary files](https://www12.statcan.gc.ca/census-recensement/2011/geo/bound-limit/bound-limit-eng.cfm)

* 2016, Dissemination area https://www150.statcan.gc.ca/n1/en/catalogue/92-169-X

* 2016, Census tract 

